name: ci

on:
  push:
    branches:
      - "main"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  build:
    permissions:
      contents: write 
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin
      REPO: shipping
      AWS_REGION: eu-central-1

    steps:
      - uses: actions/checkout@v4

      - name: Unit Tests
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          chmod +x scripts/test.sh
          bash scripts/test.sh

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x scripts/git_update_tag.sh
          bash scripts/git_update_tag.sh -v patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GROUP }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        env:
          TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          chmod +x scripts/build.sh
          bash scripts/build.sh

      - name: Push user to Docker Hub
        env:
          TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker push $GROUP/$REPO:$TAG
          
      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR Private
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Tag Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker tag ${GROUP}/${REPO}:${IMAGE_TAG} ${REGISTRY}/${REPO}:$IMAGE_TAG

      - name: push Frontend docker image to Amazon ECR Private
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker push $REGISTRY/$REPO:$IMAGE_TAG
